<?php

$labels = array();

$labels['from_outsite'] = "Der Absender dieser E-Mail ist nicht Teil ihrer Organisation. Klicken Sie nicht auf Links und Öffnen sie keine Anhänge, es sei denn Ihnen ist der Absender bekannt und Sie betrachten den Inhalt als vertrauenswürdig.";
$labels['posible_spam'] = "Die E-Mail ist möglicherweise Spam. Ihr Inhalt ist mit Vorsicht zu genießen.";
$labels['spf_fail'] = "Die Authentizität des angezeigten Absenders konnte nicht verifiziert werden.<br />Vermeiden Sie auf Links zu klicken, Anhänge zu öffnen oder persönlichen Details herauszugeben.";
