<?php

$labels = array();

$labels['from_outsite'] = "This mail originated from outside of your organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.";
$labels['posible_spam'] = "This mail has been identified as possible spam. Be extra careful while interacting with its contents.";
$labels['spf_fail'] = "The authenticity of the sender of this email could not be verified. <br> Avoid clicking links, downloading attachments or replying with personal information.";

