<?php

$labels = array();

$labels['from_outsite'] = "Este correo se originó desde fuera de su organización. No abra enlaces o adjuntos a menos que reconozca al remitente y sepa que el contenido es seguro.";
$labels['posible_spam'] = "Este correo ha sido identificado como posible SPAM. Tenga cuidado con su contenido.";
$labels['spf_fail'] = "La autenticidad del remitente no se pudo verificar. <br> Evite abrir enlaces, descargar adjuntos o responder con información personal.";
