<?php

$labels = array();

$labels['from_outsite'] = "Ce courrier provient d'une source extérieure à votre organisation. Ne cliquez pas sur les liens et n'ouvrez pas les pièces jointes à moins de reconnaître l'expéditeur et d'être certain que le contenu est sûr.";
$labels['posible_spam'] = "Ce courrier a été identifié comme potentiellement indésirable. Soyez particulièrement prudent lorsque vous interagissez avec son contenu.";
$labels['spf_fail'] = "L'authenticité de l'expéditeur de cet e-mail n'a pas pu être vérifiée. <br> Évitez de cliquer sur des liens, de télécharger des pièces jointes ou de répondre avec des informations personnelles.";
