<?php

$labels = array();

$labels['from_outsite'] = "Ez az e-mail a szervezeten kívülről származik. Ne nyisd meg a benne szereplő linkekt és csatolmányokat amennyiben nem ismered a feladót vagy nem biztos a csatolmányok megbízhatósága!";
$labels['posible_spam'] = "Ez az e-mail lehetséges spamnek lett jelölve. Bánj különös megfontossággal a tartalmával!";
$labels['spf_fail'] = "Nem sikerült ellenőrizni a feladó személyazonosságát. <br> Kerüld a linkek és csatolmányok megnyitását, illetve válaszodban a személyes adatok küldését!";
