<?php

$labels = array();

$labels['from_outsite'] = "Questo messaggio proviene
    dall'esterno della vostra organizzazione. Si consiglia di evitare
    di fare clic su eventuali link o di aprire allegati a meno che non
    si conosca il mittente e si ritenga sicuro il contenuto del
    messaggio";
$labels['posible_spam'] = "Questo messaggio è stato
    riconosciuto come potenziale SPAM. Si consiglia di essere
    estremamente cauti nell\'interagire con il relativo contenuto";
$labels['spf_fail'] = "Non è stato possibile verificare
    l'autenticità del mittente di questo messaggio.<br>Si
    consiglia di evitare di fare clic su eventuali link, scaricare
    allegati o rispondere inviando dati personali";

