<?php

$labels = array();

$labels['from_outsite'] = "Deze e-mail is afkomstig van buiten uw organisatie. Klik niet op links en open geen bijlagen tenzij u de afzender kent en weet dat de inhoud veilig is.";
$labels['posible_spam'] = "Deze mail is geïdentificeerd als mogelijke spam. Wees extra voorzichtig bij het omgaan met de inhoud ervan.";
$labels['spf_fail'] = "De authenticiteit van de afzender van deze e-mail kon niet worden geverifieerd. <br> Klik niet op links, download geen bijlagen en reageer niet met persoonlijke informatie.";
