<?php

$labels = array();

$labels['from_outsite'] = "Este e-mail foi originado de fora da sua organização. Não clique em links ou abra anexos, a menos que reconheça o remetente e saiba que o conteúdo é seguro.";
$labels['posible_spam'] = "Este e-mail foi identificado como possível spam. Seja extremamente cuidadoso ao interagir com seu conteúdo.";
$labels['spf_fail'] = "Não foi possível verificar a autenticidade do remetente deste e-mail. <br> Evite clicar em links, baixar anexos ou responder com informações pessoais.";
